

export const LOAD_PRODUCTS = "LOAD_PRODUCTS"
export const ADD_TO_CART = "ADD_T0_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CHANGE_COUNT = "CHANGE_COUNT"
export const SAVE_PRODUCT = "SAVE_PRODUCT"
export const DELETE_SAVED = "DELETE_SAVED"
export const CLEAR_CART = "CLEAR_CART"